# This workflow will run CI for nodejs related application/service

name: NodeJs CI

on: 
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-dir: '.'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: grandmasterdev/github-action-ci-nodejs-build-test@v1.0.0
        with:
          working-dir: ${{github.workspace}}

      - uses: grandmasterdev/github-action-ci-nodejs-package@v1.0.0-alpha.2
        with:
          working-dir: ${{github.workspace}}
          packager: tar
          assets: 'dist,bin,package.json,package-lock.json,cdk.context.json,cdk.json,lib'

      - uses: grandmasterdev/github-action-ci-revision-artifact@v1.0.0-beta.7
        with:
          working-dir: ${{github.workspace}}
          version-type: datehash
          artifact-repo: 'example-repo-local'
          artifact-host: ${{secrets.ARTIFACT_HOST}}
          artifact-path: 'example-repo-local/s3-av-scanner'
          artifact-token: ${{secrets.ARTIFACT_TOKEN}}
          packager-type: 'tar'

