# This workflow will run CI for nodejs related application/service

name: NodeJs CI

on: 
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-dir: '.'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: build
        run: |
          npm ci
          npm run build
          npm run test

