# This workflow will trigger on a daily basis to check aws cdk version, update them if needed and creates a pull request when its done.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions 
####
name: NPM audit fix cron

on:
  schedule:
    - cron: '0 0 * * *' # runs everyday at 12am
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  automate:
    runs-on: ubuntu-latest
    env:
      working-dir: '.'

    steps:
    - uses: actions/checkout@v2
      
    - name: npm-audit-fix
      uses: grandmasterdev/github-action-npm-audit-fix@beta
      with:
        working-dir: ${{github.workspace}}
        github-user: 'action-committer'
        github-email: 'action-committer'
        github-token: ${{github.token}}
        github-remote: 'origin'
